---

- name: Network | Debian | Apply | Applying network config w/o verifier
  ansible.builtin.systemd:
    name: 'networking.service'
    state: restarted
  ignore_errors: true
  timeout: 15

- name: Network | Debian | Apply | Updating ip used in this execution
  ansible.builtin.set_fact:
    ansible_host: "{{ post_apply_ip }}"
  when: NW.post_apply_ip is defined

- name: Network | Debian | Apply | Waiting to re-establish connection
  ansible.builtin.wait_for_connection:
    timeout: "{{ NW_HC.network_apply_timeout }}"
  register: connection_restore
  ignore_errors: true

- name: Network | Debian | Apply | Unable to connect
  ansible.builtin.fail:
    msg: 'It seems like we lost the connection to the target-host. (but might so if the ip was changed on purpose..)
    This will most probably be a configuration-issue!
    Consider using the network-verifier in the future!'
  when:
    - connection_restore.failed is defined
    - connection_restore.failed
